#!/usr/bin/env python3
"""Rasterize the game's embedded DejaVu Sans Mono (../cpp/DejaVuMono.h) into
an anti-aliased bitmap font header, at the same 20 px size wopr_render.cpp
asks FreeType for, so the bare-metal build's text matches the desktop one.

    python3 tools/gen_font.py ../cpp/DejaVuMono.h > dejavu20.h   (needs Pillow)
"""
import base64, io, re, sys
from PIL import Image, ImageFont

PX = 20
src = open(sys.argv[1]).read()
b64 = "".join(re.findall(r'"([A-Za-z0-9+/=]*)"', src.split("DEJAVU_REGULAR_FONT_B64[] =", 1)[1].split(";", 1)[0]))
font = ImageFont.truetype(io.BytesIO(base64.b64decode(b64)), PX)
ascent, descent = font.getmetrics()
cell_w = round(font.getlength("M"))
cell_h = ascent + descent
chars = [chr(c) for c in range(32, 127)] + ["←", "↑", "→", "↓"]

out = sys.stdout
out.write("// Generated by tools/gen_font.py from DejaVu Sans Mono (see ../cpp/DejaVuMono.h).\n")
out.write("// 8-bit coverage per pixel. Glyphs: ASCII 32..126, then U+2190..U+2193.\n#pragma once\n#include <stdint.h>\n")
out.write(f"#define FONT_CELL_W {cell_w}\n#define FONT_CELL_H {cell_h}\n#define FONT_GLYPHS {len(chars)}\n")
out.write("static const uint8_t font_cov[FONT_GLYPHS][FONT_CELL_H][FONT_CELL_W] = {\n")
for ch in chars:
    img = Image.new("L", (cell_w, cell_h), 0)
    from PIL import ImageDraw
    ImageDraw.Draw(img).text((0, ascent), ch, font=font, fill=255, anchor="ls")
    px = img.load()
    rows = ["{" + ",".join(str(px[x, y]) for x in range(cell_w)) + "}" for y in range(cell_h)]
    out.write(" {" + ",".join(rows) + "}, // U+%04X\n" % ord(ch))
out.write("};\n")
