name: Build and Release Willy the Worm

on:
  push:
    branches:
      - main
      - dev

jobs:
  create-source-release:
    permissions:
      contents: write # Required for creating releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Source Archive
        run: |
          zip -r willy-the-worm-source.zip . -x '*.git*'
      
      - name: Upload Source Archive
        uses: actions/upload-artifact@v4
        with:
          name: source-package
          path: willy-the-worm-source.zip

  build-windows-installer:
    runs-on: windows-latest
    needs: create-source-release
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install cx_Freeze
          pip install wheel setuptools

      - name: Create Runtime Hook
        run: |
          echo 'import os
          import sys
          os.environ["SDL_VIDEODRIVER"] = "windows"
          if getattr(sys, "frozen", False):
              os.chdir(os.path.dirname(sys.executable))' > rthooks.py
          
      - name: Create Windows Executables
        run: |
          pyinstaller --onefile --noconsole --icon=icon.ico --add-data "levels.json;." --add-data "original_levels.json;." --add-data "willy.chr;." --add-data "audio/*;audio/" --runtime-hook rthooks.py --collect-all pygame willy.py
          pyinstaller --onefile --noconsole --icon=icon.ico --add-data "levels.json;." --add-data "original_levels.json;." --add-data "willy.chr;." --add-data "audio/*;audio/" --runtime-hook rthooks.py --collect-all pygame edwilly.py
          pyinstaller --onefile --noconsole --icon=icon.ico --add-data "levels.json;." --add-data "original_levels.json;." --add-data "willy.chr;." --add-data "audio/*;audio/" --runtime-hook rthooks.py --collect-all pygame willy_qt.py

      - name: Install WiX Toolset
        run: |
          mkdir wix
          cd wix
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix311-binaries.zip"
          Expand-Archive wix311-binaries.zip -DestinationPath .
          echo "$pwd" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Create MSI Installer
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="Willy the Worm" Language="1033" Version="1.0.0" Manufacturer="Jason Hall" UpgradeCode="D0A8E7F1-3B92-4C67-B8E5-1A4F26D95C03">
              <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
              <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />
              <MediaTemplate EmbedCab="yes" />
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="Willy the Worm">
                    <Component Id="MainExecutable" Guid="E2A49E3F-B0A4-45D9-8923-A4A6D3EA2944">
                      <File Id="WillyEXE" Name="willy.exe" Source="dist/willy.exe" KeyPath="yes"/>
                      <File Id="EdWillyEXE" Name="edwilly.exe" Source="dist/edwilly.exe"/>
                      <File Id="willyqt" Name="willy_qt.exe" Source="dist/willy_qt.exe"/>
                      <File Id="README" Name="README.md" Source="README.md"/>
                      <File Id="OriginalLevels" Name="original_levels.json" Source="original_levels.json" />
                      <File Id="Levels" Name="levels.json" Source="levels.json" />
                      <File Id="WIKI" Name="wiki.md" Source="wiki.md" />
                      <File Id="CHARACTERS" Name="willy.chr" Source="willy.chr" />
                      <File Id="LICENSE" Name="LICENSE.md" Source="LICENSE.md" />
                      <File Id="CONTRIBUTION" Name="contribution.md" Source="contribution.md" />
                      <File Id="ICON" Name="icon.png" Source="icon.png" />
                      <File Id="ICON_WINDOWS" Name="icon.ico" Source="icon.ico" />
                      <File Id="WILLYPY" Name="willy.py" Source="willy.py" />
                      <File Id="EDWILLYPY" Name="edwilly.py" Source="edwilly.py" />
                      <File Id="WILLYQTPY" Name="willy_qt.py" Source="willy_qt.py" />
                      <File Id="REQUIREMENTS" Name="requirements.txt" Source="requirements.txt" />
                    </Component>
                    <Directory Id="AudioDir" Name="audio">
                      <Component Id="AudioFiles" Guid="7B9DD5C8-2C1E-4B7F-9D47-F5A4D653809C">
                        <File Id="Bell" Name="bell.mp3" Source="audio/bell.mp3" />
                        <File Id="Boop" Name="boop.mp3" Source="audio/boop.mp3" />
                        <File Id="Jump" Name="jump.mp3" Source="audio/jump.mp3" />
                        <File Id="Ladder" Name="ladder.mp3" Source="audio/ladder.mp3" />
                        <File Id="Present" Name="present.mp3" Source="audio/present.mp3" />
                        <File Id="Tack" Name="tack.mp3" Source="audio/tack.mp3" />
                      </Component>
                    </Directory>
                  </Directory>
                </Directory>      
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ApplicationProgramsFolder" Name="Willy the Worm">
                    <Component Id="ApplicationShortcuts" Guid="F8A427D5-9EE6-4B85-A543-E2B8C5D478B1">
                      <Shortcut Id="WillyStartMenu" Name="Willy the Worm" Target="[INSTALLFOLDER]willy.exe" WorkingDirectory="INSTALLFOLDER" Icon="icon.ico"/>
                      <Shortcut Id="EdWillyStartMenu" Name="Willy Level Editor" Target="[INSTALLFOLDER]edwilly.exe" WorkingDirectory="INSTALLFOLDER" Icon="icon.ico"/>
                      <Shortcut Id="WillyControlPanel" Name="Willy Control Panel" Target="[INSTALLFOLDER]willy_qt.exe" WorkingDirectory="INSTALLFOLDER" Icon="icon.ico"/>
                      <RemoveFolder Id="ApplicationProgramsFolder" On="uninstall"/>
                      <RegistryValue Root="HKCU" Key="Software\WillyTheWorm" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                    </Component>
                  </Directory>
                </Directory>
              </Directory>
              <Feature Id="ProductFeature" Title="WillyTheWorm" Level="1">
                <ComponentRef Id="MainExecutable" />
                <ComponentRef Id="AudioFiles" />
                <ComponentRef Id="ApplicationShortcuts" />
              </Feature>
              <Icon Id="WillyIcon.exe" SourceFile="icon.ico" />
              <Icon Id="EdWillyIcon.exe" SourceFile="icon.ico" />
            </Product>
          </Wix>' > installer.wxs

          candle installer.wxs
          light installer.wixobj -out WillyTheWorm.msi

      - name: Save Installer Path
        id: save_path
        run: echo "path=WillyTheWorm.msi" >> $GITHUB_OUTPUT
      
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: WillyTheWorm.msi

  create-release:
    needs: [create-source-release, build-windows-installer]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            source-package/willy-the-worm-source.zip
            windows-installer/WillyTheWorm.msi
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
